server:
  port: 8001  #客户端的端口没有要求


spring:
  application:
    name: eureka-client-a

#注册的含义：将自己的一些信息发送过去
eureka:
  client:
    #设置客户端注册的eureka的地址
    service-url:
      defaultZone: http://eureka1:8761/eureka
    #是否使用eureka进行注册
    register-with-eureka: true
    #客户端是否拉取注册服务列表
    fetch-registry: true
    #为了缓解服务列表的脏读问题（时间越短脏读越少  性能消耗越大）
    registry-fetch-interval-seconds: 10
  instance:
    #应用的主机名称
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: true


#server:
##  port: 8001  #客户端的端口没有要求
##spring:
##  application:
##    name: eureka-client-a
##
###注册的含义：将自己的一些信息发送过去
##eureka:
##  client:
##    #设置客户端注册的eureka的地址
##    service-url:
##      defaultZone: http://eureka1:8761/eureka
##    #是否使用eureka进行注册
##    register-with-eureka: true
##    #客户端是否拉取注册服务列表
##    fetch-registry: true
##    #为了缓解服务列表的脏读问题（时间越短脏读越少  性能消耗越大）
##    registry-fetch-interval-seconds: 10
##  instance:
##    #应用的主机名称
##    hostname: localhost
##    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
##    lease-renewal-interval-in-seconds: 10
##    prefer-ip-address: true

#server:
#  port: 8001  #客户端的端口没有要求
#spring:
#  application:
#    name: eureka-client-a
#
##注册的含义：将自己的一些信息发送过去
#eureka:
#  client:
#    #设置客户端注册的eureka的地址
#    service-url:
#      defaultZone: http://eureka1:8761/eureka,http://eureka2:8762/eureka,http://eureka3:8763/eureka
#    #是否使用eureka进行注册
#    register-with-eureka: true
#    #客户端是否拉取注册服务列表
#    fetch-registry: true
#    #为了缓解服务列表的脏读问题（时间越短脏读越少  性能消耗越大）
#    registry-fetch-interval-seconds: 10
#  instance:
#    #应用的主机名称
#    hostname: localhost
#    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
#    lease-renewal-interval-in-seconds: 10
#    prefer-ip-address: true


