server:
  port: 8013

spring:
  application:
    name: ribbon-consumer

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
#\u8BBF\u95EE\u4E0D\u540C\u7684\u670D\u52A1\u53EF\u4EE5\u4F7F\u7528\u4E0D\u540C\u7684\u7B97\u6CD5\u89C4\u5219
ribbon-provider: #\u5148\u5199\u670D\u52A1\u63D0\u4F9B\u8005\u7684\u5E94\u7528\u540D\u79F0
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

ribbon:
  eager-load:
    #ribbon\u9700\u8981\u53BBeureka\u4E2D\u62C9\u53D6\u670D\u52A1\u5217\u8868 \u5982\u679C\u4E3Afalse\uFF0C\u5219\u8C03\u7528\u7684\u65F6\u5019\u518D\u53BB\u62C9\u53D6   \u5982\u679C\u4E3Atrue\uFF0C\u5219\u542F\u52A8\u7684\u65F6\u5019\u5C31\u53BB\u83B7\u53D6
    enabled: true
  eureka:
    enabled: true
  http: #\u6211\u4EEC\u4F7F\u7528ribbon  \u7528\u7684\u662FrestTemplate\u53D1\u8BF7\u6C42 java.net.HttpUrlConnection \u53D1\u7684\u8BF7\u6C42  \u5F88\u65B9\u4FBF \u4F46\u662F\u4E0D\u652F\u6301\u8FDE\u63A5\u6C60
        #\u6211\u4EEC\u8FD8\u53EF\u4EE5\u4F7F\u7528httpClient \u5B83\u652F\u6301\u6570\u636E\u5E93\u8FDE\u63A5\u6C60  \u6548\u7387\u66F4\u597D
    client:
      enabled: true
  okhttp:
    enabled: true